In [34]:
import os
import re
import string
import spacy
import json
import pandas
import numpy as np
import pickle as pkl
import xml.etree.ElementTree as ET

from tqdm import tqdm
from keras.preprocessing.sequence import pad_sequences
from process_text import process_text

In [35]:
nlp = spacy.load('en')
relevance2label = {'Good': 0, 'PotentiallyUseful': 1, 'Bad': 2}

In [36]:
def SemEval16or17_sample(filename):
    root = ET.parse(filename).getroot()
    for thread in root.findall('Thread'):
        question = thread.find('RelQuestion')
        
        q_id = question.get('RELQ_ID')
        q_category = question.get('RELQ_CATEGORY')
        q_date = question.get('RELQ_DATE')
        q_userid = question.get('RELQ_USERID')
        q_username = question.get('RELQ_USERNAME')
        
        q_subject = question.find('RelQSubject').text or ''
        q_body = question.find('RelQBody').text or ''
        
        for relcomment in thread.findall('RelComment'):
            c_id = relcomment.get('RELC_ID')
            c_date = relcomment.get('RELC_DATE')
            c_userid = relcomment.get('RELC_USERID')
            c_username = relcomment.get('RELC_USERNAME')
            Relevance = relcomment.get('RELC_RELEVANCE2RELQ')
            cTEXT = relcomment.find('RelCText').text or ''
#             if len(q_subject) == 0 or len(q_body) == 0 or len(cTEXT) == 0:
#                 print(c_id, len(q_subject), len(q_body), len(cTEXT))
#                 continue
            yield [q_id, c_id, q_category, q_subject, q_body, cTEXT, Relevance, q_userid, c_userid]

In [37]:
# create dataFrame
columns = ['q_id', 'c_id', 'q_category', 'q_subject', 'q_body', 'cTEXT', 'Relevance', 'q_userid', 'c_userid']

In [38]:
filepath = '../raw_data'
all_samples = {}
data_filename_list = os.listdir(filepath)

for name in data_filename_list:
    print('\n\t\t处理文件：%s\n' % name)
    filename = os.path.join(filepath, name)
    samples = SemEval16or17_sample(filename)
#     samples = [sample for sample in tqdm(samples)]
    all_samples[name] = pandas.DataFrame(columns=columns, data=samples)
    all_samples[name].head()

		处理文件：15dev.xml


		处理文件：15test.xml


		处理文件：15train.xml


		处理文件：16dev.xml


		处理文件：16test.xml


		处理文件：16train1.xml


		处理文件：16train2.xml


		处理文件：17test.xml

In [39]:
all_samples['15dev.xml'].head(5)

,q_id,c_id,q_category,q_subject,q_body,cTEXT,Relevance,q_userid,c_userid
0,Q2481,Q2481_C1,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,If you are single then its ok you can enjoy.,PotentiallyUseful,U8902,U7263
1,Q2481,Q2481_C2,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,depends on where the accommodation is.. how ma...,Good,U8902,U604
2,Q2481,Q2481_C3,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,If the company is from Oil and Gas Industry or...,Good,U8902,U2316
3,Q2481,Q2481_C4,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,Transport in the city is a nightmare.,Good,U8902,U5547
4,Q2481,Q2481_C5,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,And life her is so relaxed that bachelors are ...,Bad,U8902,U5547

In [40]:
keys_lists = all_samples.keys()
all_samples_concate = {}
for key in keys_lists:
    print(key)
    samples = all_samples[key]
    
    def mark_func(x):
        rel = x['Relevance']
        q_userid = x['q_userid']
        c_userid = x['c_userid']
        if q_userid == c_userid:
            return 1
        else:
            return 0
    
    def mark_func2(x):
        rel = x['Relevance']
        q_userid = x['q_userid']
        c_userid = x['c_userid']
        if q_userid == c_userid and rel == 'Good':
            return 1
        else:
            return 0
    
    qc_mark = samples.apply(mark_func, axis=1)
    qc_mark2 = samples.apply(mark_func2, axis=1)
    samples['qc_mark'] = qc_mark
    
    print('-----------------------------------')
#     print(qc_mark[:10], qc_mark2[:10])
    print(qc_mark.sum(), qc_mark2.sum())
    print('-----------------------------------\n\n')

15dev.xml
-----------------------------------
191 23
-----------------------------------


15test.xml
-----------------------------------
264 31
-----------------------------------


15train.xml
-----------------------------------
2199 318
-----------------------------------


16dev.xml
-----------------------------------
393 40
-----------------------------------


16test.xml
-----------------------------------
560 54
-----------------------------------


16train1.xml
-----------------------------------
2152 229
-----------------------------------


16train2.xml
-----------------------------------
584 58
-----------------------------------


17test.xml
-----------------------------------
480 67
-----------------------------------

In [41]:
keys_lists = all_samples.keys()
all_samples_concate = {}
for key in keys_lists:
    print(key)
    samples = all_samples[key]
    qc_mark = samples.groupby('qc_mark')
    qc_mark = [a for a in qc_mark]
    qc_mark = {a[0]: a[1] for a in qc_mark}
    print(qc_mark[1]['c_id'])
    print('===================\n\n')

15dev.xml
10      Q2481_C11
16       Q2483_C1
50       Q2491_C2
58       Q2492_C6
60       Q2492_C8
61       Q2492_C9
65       Q2493_C2
67       Q2493_C4
71       Q2494_C2
73       Q2494_C4
79       Q2497_C1
81       Q2497_C3
84       Q2498_C3
95       Q2501_C3
122      Q2507_C7
162      Q2514_C5
186      Q2522_C3
197      Q2526_C2
198      Q2526_C3
200      Q2526_C5
205      Q2527_C3
220      Q2532_C2
235      Q2535_C5
261      Q2538_C3
280      Q2541_C4
282      Q2542_C2
283      Q2542_C3
291      Q2544_C1
298      Q2544_C8
299      Q2544_C9
          ...
1270    Q2724_C16
1284     Q2729_C2
1289     Q2730_C5
1292     Q2731_C3
1307     Q2733_C8
1308     Q2733_C9
1312     Q2734_C4
1324     Q2737_C2
1325     Q2737_C3
1328     Q2737_C6
1333     Q2738_C4
1344    Q2739_C10
1345    Q2739_C11
1351     Q2740_C5
1359     Q2743_C3
1387     Q2747_C6
1393     Q2749_C1
1395     Q2749_C3
1411     Q2753_C2
1412     Q2753_C3
1415     Q2753_C6
1417     Q2753_C8
1429     Q2755_C9
1431     Q2756_C1
1445     Q2758_C3
1452     Q2760_C6
1457     Q2761_C3
1472    Q2761_C18
1480    Q2761_C26
1508     Q2765_C4
Name: c_id, Length: 191, dtype: object
===================


15test.xml
0        Q2772_C1
9        Q2774_C3
18       Q2776_C2
20       Q2776_C4
27       Q2779_C3
28       Q2779_C4
29       Q2779_C5
55      Q2779_C31
61      Q2779_C37
64       Q2780_C2
84      Q2782_C12
86      Q2782_C14
90       Q2785_C1
93       Q2786_C3
96       Q2787_C3
100      Q2788_C2
124     Q2792_C13
128     Q2792_C17
145      Q2793_C2
147      Q2793_C4
164      Q2797_C5
171      Q2798_C7
173      Q2798_C9
177     Q2798_C13
183     Q2798_C19
191      Q2799_C2
194      Q2799_C5
205      Q2803_C3
207      Q2803_C5
224      Q2806_C3
          ...
1646    Q3031_C23
1648    Q3031_C25
1651    Q3031_C28
1654     Q3034_C1
1657     Q3034_C4
1664     Q3036_C4
1670     Q3037_C2
1679     Q3040_C2
1681     Q3041_C1
1694     Q3045_C2
1721     Q3050_C2
1726     Q3051_C3
1727     Q3052_C1
1731     Q3053_C1
1745     Q3058_C2
1751     Q3060_C3
1753     Q3060_C5
1755     Q3061_C2
1767     Q3062_C3
1785     Q3069_C6
1811     Q3076_C4
1812     Q3076_C5
1814     Q3076_C7
1816     Q3076_C9
1836     Q3079_C2
1839     Q3080_C3
1841     Q3080_C5
1843     Q3081_C2
1859     Q3085_C1
1862     Q3085_C4
Name: c_id, Length: 264, dtype: object
===================


15train.xml
1            Q1_C2
2            Q1_C3
6            Q2_C1
13           Q5_C5
15           Q5_C7
32           Q9_C1
48          Q12_C3
55          Q15_C1
64          Q17_C4
69          Q18_C3
73          Q19_C2
76          Q19_C5
83         Q19_C12
89          Q20_C5
99         Q20_C15
104         Q22_C2
107         Q22_C5
113         Q23_C4
115         Q24_C2
117         Q24_C4
119         Q24_C6
120         Q24_C7
133         Q28_C1
152         Q31_C1
154         Q31_C3
155         Q31_C4
157         Q32_C2
158         Q32_C3
162         Q33_C4
163         Q33_C5
           ...
14745     Q2461_C1
14763     Q2463_C2
14773    Q2463_C12
14774    Q2463_C13
14775    Q2463_C14
14777    Q2463_C16
14778    Q2463_C17
14780    Q2463_C19
14783    Q2463_C22
14785    Q2463_C24
14786    Q2463_C25
14788    Q2463_C27
14790    Q2463_C29
14792    Q2463_C31
14794    Q2463_C33
14797    Q2463_C36
14807     Q2464_C4
14822     Q2468_C4
14830     Q2471_C2
14835     Q2472_C4
14837     Q2472_C6
14839     Q2472_C8
14871     Q2476_C2
14876     Q2478_C3
14879     Q2478_C6
14882     Q2478_C9
14885    Q2478_C12
14887    Q2478_C14
14889    Q2478_C16
14890    Q2478_C17
Name: c_id, Length: 2199, dtype: object
===================


16dev.xml
5        Q268_R16_C6
6        Q268_R16_C7
7        Q268_R16_C8
8        Q268_R16_C9
12        Q269_R3_C3
31       Q269_R10_C2
33       Q269_R10_C4
36       Q269_R10_C7
38       Q269_R10_C9
49      Q269_R26_C10
50       Q269_R27_C1
51       Q269_R27_C2
52       Q269_R27_C3
54       Q269_R27_C5
68       Q270_R37_C9
71       Q270_R47_C2
73       Q270_R47_C4
77       Q270_R47_C8
86       Q270_R51_C7
99      Q270_R58_C10
107      Q270_R64_C8
122      Q271_R57_C3
139     Q271_R59_C10
140      Q271_R63_C1
143      Q271_R63_C4
146      Q271_R63_C7
147      Q271_R63_C8
149     Q271_R63_C10
151      Q271_R70_C2
175      Q272_R14_C6
            ...
2252     Q314_R25_C3
2254     Q314_R25_C5
2255     Q314_R25_C6
2257     Q314_R25_C8
2259    Q314_R25_C10
2269    Q315_R21_C10
2280     Q315_R35_C1
2281     Q315_R35_C2
2291     Q315_R36_C2
2293     Q315_R36_C4
2296     Q315_R36_C7
2311     Q315_R46_C2
2314     Q315_R46_C5
2319    Q315_R46_C10
2328     Q315_R47_C9
2334      Q316_R2_C5
2336      Q316_R2_C7
2341      Q316_R3_C2
2354      Q316_R8_C5
2356      Q316_R8_C7
2358      Q316_R8_C9
2372     Q316_R17_C3
2376     Q316_R17_C7
2378     Q316_R17_C9
2387     Q316_R20_C8
2398     Q316_R25_C9
2408     Q316_R31_C9
2431     Q317_R23_C2
2433     Q317_R23_C4
2436     Q317_R23_C7
Name: c_id, Length: 393, dtype: object
===================


16test.xml
5         Q318_R6_C6
12       Q318_R52_C3
14       Q318_R52_C5
46        Q319_R6_C7
53       Q319_R40_C4
56       Q319_R40_C7
59      Q319_R40_C10
62       Q319_R44_C3
63       Q319_R44_C4
67       Q319_R44_C8
73        Q320_R1_C4
74        Q320_R1_C5
77        Q320_R1_C8
79       Q320_R1_C10
80        Q320_R2_C1
83        Q320_R2_C4
84        Q320_R2_C5
101       Q320_R8_C2
107       Q320_R8_C8
109      Q320_R8_C10
111      Q320_R10_C2
114      Q320_R10_C5
116      Q320_R10_C7
124      Q320_R12_C5
131      Q320_R20_C2
140       Q321_R2_C1
147       Q321_R2_C8
152      Q321_R17_C3
189      Q322_R9_C10
199     Q322_R32_C10
            ...
3112     Q385_R25_C3
3116     Q385_R25_C7
3124     Q385_R30_C5
3126     Q385_R30_C7
3132     Q385_R31_C3
3135     Q385_R31_C6
3138     Q385_R31_C9
3143     Q385_R34_C4
3144     Q385_R34_C5
3147     Q385_R34_C8
3148     Q385_R34_C9
3173     Q386_R10_C4
3175     Q386_R10_C6
3177     Q386_R10_C8
3183     Q386_R19_C4
3185     Q386_R19_C6
3186     Q386_R19_C7
3188     Q386_R19_C9
3211     Q386_R47_C2
3217     Q386_R47_C8
3220      Q387_R7_C1
3223      Q387_R7_C4
3225      Q387_R7_C6
3229     Q387_R7_C10
3243     Q387_R30_C4
3244     Q387_R30_C5
3253     Q387_R41_C4
3259    Q387_R41_C10
3262     Q387_R44_C3
3264     Q387_R44_C5
Name: c_id, Length: 560, dtype: object
===================


16train1.xml
1            Q1_R1_C2
3            Q1_R1_C4
27           Q1_R8_C8
37          Q1_R10_C8
43          Q1_R22_C4
71          Q1_R32_C2
74          Q1_R32_C5
75          Q1_R32_C6
81          Q1_R43_C2
85          Q1_R43_C6
88          Q1_R43_C9
90          Q1_R46_C1
102         Q2_R20_C3
108         Q2_R20_C9
127         Q2_R32_C8
128         Q2_R32_C9
129        Q2_R32_C10
136         Q2_R46_C7
139        Q2_R46_C10
144         Q2_R60_C5
146         Q2_R60_C7
147         Q2_R60_C8
149        Q2_R60_C10
155         Q2_R65_C6
163         Q2_R74_C4
172         Q2_R80_C3
177         Q2_R80_C8
213         Q3_R46_C4
216         Q3_R46_C7
219        Q3_R46_C10
             ...
13910     Q198_R36_C1
13931      Q199_R4_C2
13933      Q199_R4_C4
13935      Q199_R4_C6
13937      Q199_R4_C8
13955      Q199_R7_C6
13961     Q199_R15_C2
13963     Q199_R15_C4
13965     Q199_R15_C6
13968     Q199_R15_C9
13969    Q199_R15_C10
13972     Q199_R27_C3
13977     Q199_R27_C8
13983     Q199_R36_C4
13984     Q199_R36_C5
13985     Q199_R36_C6
13988     Q199_R36_C9
13992     Q199_R38_C3
13995     Q199_R38_C6
14001     Q199_R56_C2
14037     Q200_R16_C8
14039    Q200_R16_C10
14047     Q200_R18_C8
14048     Q200_R18_C9
14056     Q200_R25_C7
14064     Q200_R28_C5
14067     Q200_R28_C8
14070     Q200_R29_C1
14071     Q200_R29_C2
14096     Q200_R35_C7
Name: c_id, Length: 2152, dtype: object
===================


16train2.xml
12       Q201_R29_C3
13       Q201_R29_C4
15       Q201_R29_C6
17       Q201_R29_C8
21       Q201_R35_C2
26       Q201_R35_C7
27       Q201_R35_C8
29      Q201_R35_C10
42       Q202_R11_C3
49      Q202_R11_C10
63       Q202_R20_C4
65       Q202_R20_C6
66       Q202_R20_C7
71       Q202_R37_C2
79      Q202_R37_C10
86       Q202_R38_C7
87       Q202_R38_C8
91        Q203_R2_C2
94        Q203_R2_C5
95        Q203_R2_C6
101      Q203_R12_C2
141      Q204_R32_C2
143      Q204_R32_C4
145      Q204_R32_C6
165      Q204_R59_C6
171      Q205_R41_C2
176      Q205_R41_C7
178      Q205_R41_C9
190      Q206_R27_C1
194      Q206_R27_C5
            ...
3543      Q265_R3_C4
3567      Q265_R7_C8
3571      Q265_R9_C2
3613     Q265_R20_C4
3614     Q265_R20_C5
3616     Q265_R20_C7
3618     Q265_R20_C9
3621     Q266_R11_C2
3624     Q266_R11_C5
3626     Q266_R11_C7
3628     Q266_R11_C9
3635     Q266_R31_C6
3664     Q266_R51_C5
3666     Q266_R51_C7
3668     Q266_R51_C9
3671     Q266_R61_C2
3672     Q266_R61_C3
3676     Q266_R61_C7
3678     Q266_R61_C9
3691      Q267_R1_C2
3695      Q267_R1_C6
3703      Q267_R4_C4
3709     Q267_R4_C10
3713      Q267_R6_C4
3716      Q267_R6_C7
3721     Q267_R14_C2
3725     Q267_R14_C6
3748     Q267_R28_C9
3749    Q267_R28_C10
3751     Q267_R32_C2
Name: c_id, Length: 584, dtype: object
===================


17test.xml
1        Q388_R14_C2
11       Q388_R21_C2
13       Q388_R21_C4
16       Q388_R21_C7
24       Q388_R23_C5
26       Q388_R23_C7
31       Q388_R28_C2
35       Q388_R28_C6
39      Q388_R28_C10
41       Q388_R31_C2
43       Q388_R31_C4
47       Q388_R31_C8
53       Q388_R42_C4
57       Q388_R42_C8
69      Q388_R45_C10
76       Q388_R48_C7
78       Q388_R48_C9
85        Q389_R7_C6
89       Q389_R7_C10
92       Q389_R25_C3
95       Q389_R25_C6
105      Q389_R38_C6
112      Q389_R39_C3
114      Q389_R39_C5
117      Q389_R39_C8
118      Q389_R39_C9
120      Q390_R16_C1
122      Q390_R16_C3
124      Q390_R16_C5
125      Q390_R16_C6
            ...
2758     Q472_R30_C9
2777     Q473_R12_C8
2791     Q474_R21_C2
2798     Q474_R21_C9
2803     Q474_R57_C4
2807     Q474_R57_C8
2813     Q474_R69_C4
2821    Q474_R101_C2
2831      Q475_R9_C2
2836      Q475_R9_C7
2839     Q475_R9_C10
2841     Q475_R15_C2
2845     Q475_R15_C6
2849    Q475_R15_C10
2851     Q475_R17_C2
2853     Q475_R17_C4
2856     Q475_R17_C7
2857     Q475_R17_C8
2859    Q475_R17_C10
2874     Q475_R31_C5
2892     Q475_R45_C3
2895     Q475_R45_C6
2897     Q475_R45_C8
2900     Q475_R54_C1
2902     Q475_R54_C3
2913     Q475_R56_C4
2916     Q475_R56_C7
2920     Q475_R72_C1
2924     Q475_R72_C5
2926     Q475_R72_C7
Name: c_id, Length: 480, dtype: object
===================

# concate q_subject and q_body

In [42]:
keys_lists = all_samples.keys()
all_samples_concate = {}
for key in keys_lists:
    print(key)
    samples = all_samples[key]
    qTEXT = samples['q_subject'] + ' S_E_P ' + samples['q_body']
    samples['qTEXT'] = qTEXT
    all_samples_concate[key] = samples

15dev.xml
15test.xml
15train.xml
16dev.xml
16test.xml
16train1.xml
16train2.xml
17test.xml

In [43]:
print(all_samples_concate['15dev.xml'].iloc[1, :])

q_id                                                      Q2481
c_id                                                   Q2481_C2
q_category                                        Life in Qatar
q_subject                                   from DUBAI to QATAR
q_body        i am currently working here in dubai and i got...
cTEXT         depends on where the accommodation is.. how ma...
Relevance                                                  Good
q_userid                                                  U8902
c_userid                                                   U604
qc_mark                                                       0
qTEXT         from DUBAI to QATAR S_E_P i am currently worki...
Name: 1, dtype: object

In [44]:
# category2index and relevance2index
assist_path = '../assist'

with open(os.path.join(assist_path, 'Qcategory_dic.json')) as fq, \
     open(os.path.join(assist_path, 'Relevance_dic.json')) as fr:
    Qcategory_dic = json.load(fq)
    Relevance_dic = json.load(fr)

In [45]:
import copy

for key in keys_lists:
    print(key)
    samples = all_samples_concate[key]
    samples['cate_index'] = samples['q_category'].apply(lambda x: Qcategory_dic[x])
    samples['rel_index'] = samples['Relevance'].apply(lambda x: Relevance_dic[x])
    Relevance_dic_v2 = copy.copy(Relevance_dic)
    Relevance_dic_v2['Bad'] = 1
    samples['Rrel_index'] = samples['Relevance'].apply(lambda x: Relevance_dic_v2[x])

15dev.xml
15test.xml
15train.xml
16dev.xml
16test.xml
16train1.xml
16train2.xml
17test.xml

In [46]:
all_samples_concate['15dev.xml'].head(2)

,q_id,c_id,q_category,q_subject,q_body,cTEXT,Relevance,q_userid,c_userid,qc_mark,qTEXT,cate_index,rel_index,Rrel_index
0,Q2481,Q2481_C1,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,If you are single then its ok you can enjoy.,PotentiallyUseful,U8902,U7263,0,from DUBAI to QATAR S_E_P i am currently worki...,9,1,1
1,Q2481,Q2481_C2,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,depends on where the accommodation is.. how ma...,Good,U8902,U604,0,from DUBAI to QATAR S_E_P i am currently worki...,9,0,0

In [47]:
print(all_samples_concate['16train1.xml']['rel_index'].describe())
print(all_samples_concate['16train1.xml']['Rrel_index'].describe())

count    14110.000000
mean         1.076187
std          0.905449
min          0.000000
25%          0.000000
50%          1.000000
75%          2.000000
max          2.000000
Name: rel_index, dtype: float64
count    14110.000000
mean         0.625301
std          0.484062
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: Rrel_index, dtype: float64

In [48]:
test_samples = all_samples_concate['15train.xml']
cond = test_samples['q_id'] == 'Q136'
print(test_samples[cond])

     q_id     c_id           q_category q_subject  \
784  Q136  Q136_C1  Qatar Living Lounge

                                                q_body       cTEXT Relevance  \
784  Mick Hucknall apologises to 1;000 women he sle...  Who knows?       Bad

    q_userid c_userid  qc_mark  \
784     U268    U5547        0

                                                 qTEXT  cate_index  rel_index  \
784   S_E_P Mick Hucknall apologises to 1;000 women...           3          2

     Rrel_index
784           1

In [49]:
# tokenize (with lemm)
import nltk

wn_lemmatizer = nltk.stem.WordNetLemmatizer()

for key in keys_lists:
    print(key)
    samples = all_samples_concate[key]
#     samples['q_sub_token'] = samples['q_subject'].apply(lambda x: nltk.word_tokenize(x))
#     samples['q_body_token'] = samples['q_body'].apply(lambda x: nltk.word_tokenize(x))
    samples['qTEXT_token'] = samples['qTEXT'].apply(lambda x: nltk.word_tokenize(x.lower()))
    samples['cTEXT_token'] = samples['cTEXT'].apply(lambda x: nltk.word_tokenize(x.lower()))
    
    # 计算相对位置序列
    samples['q_position_index'] = samples['qTEXT_token'].apply(lambda x: [i for i in range(len(x))])
    samples['c_position_index'] = samples['cTEXT_token'].apply(lambda x: [i for i in range(len(x))])
    
    # 计算segment
    def seg_transformer(sent):
        index = sent.index('s_e_p')
        return [0]*(index+1) + [1]*(len(sent)-index-1)
    
    samples['q_segment_index'] = samples['qTEXT_token'].apply(seg_transformer)

    
#     samples['q_sub_lemma'] = samples['q_sub_token'].apply(lambda tokens: [wn_lemmatizer.lemmatize(x) for x in tokens])
#     samples['q_body_lemma'] = samples['q_body_token'].apply(lambda tokens: [wn_lemmatizer.lemmatize(x) for x in tokens])
    samples['qTEXT_lemma'] = samples['qTEXT_token'].apply(lambda tokens: [wn_lemmatizer.lemmatize(x) for x in tokens])
    samples['cTEXT_lemma'] = samples['cTEXT_token'].apply(lambda tokens: [wn_lemmatizer.lemmatize(x) for x in tokens])
    
    samples['qTEXT_lemma_pro'] = samples['qTEXT'].apply(process_text)
    samples['cTEXT_lemma_pro'] = samples['cTEXT'].apply(process_text)

15dev.xml
15test.xml
15train.xml
16dev.xml
16test.xml
16train1.xml
16train2.xml
17test.xml

In [50]:
all_samples_concate['15dev.xml'].head(2)

,q_id,c_id,q_category,q_subject,q_body,cTEXT,Relevance,q_userid,c_userid,qc_mark,...,Rrel_index,qTEXT_token,cTEXT_token,q_position_index,c_position_index,q_segment_index,qTEXT_lemma,cTEXT_lemma,qTEXT_lemma_pro,cTEXT_lemma_pro
0,Q2481,Q2481_C1,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,If you are single then its ok you can enjoy.,PotentiallyUseful,U8902,U7263,0,...,1,"[from, dubai, to, qatar, s_e_p, i, am, current...","[if, you, are, single, then, its, ok, you, can...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]","[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[from, dubai, to, qatar, s_e_p, i, am, current...","[if, you, are, single, then, it, ok, you, can,...","[from, dubai, to, qatar, s, _, e, _, p, i, am,...","[if, you, are, single, then, it, ok, you, can,..."
1,Q2481,Q2481_C2,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,depends on where the accommodation is.. how ma...,Good,U8902,U604,0,...,0,"[from, dubai, to, qatar, s_e_p, i, am, current...","[depends, on, where, the, accommodation, is..,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[from, dubai, to, qatar, s_e_p, i, am, current...","[depends, on, where, the, accommodation, is..,...","[from, dubai, to, qatar, s, _, e, _, p, i, am,...","[depends, on, where, the, accommodation, is, ...."

In [51]:
char2index = {key: value+1 for value, key in enumerate(string.ascii_letters + string.digits + string.punctuation)}
char2index['//'] = len(char2index) + 1

def count_word_number(text, word_count):
    for token in text:
        if token in word_count:
            word_count[token] += 1
        else:
            word_count[token] = 1

def char_tokenizer(text):
    char_text = []
    for token in text:
        token_ = []
        if token == 's_e_p':
            token_.append(char2index['//'])
        else:
            for c in token:
                if c not in char2index:
                    char2index[c] = len(char2index)+1
                token_.append(char2index[c])
        char_text.append(token_)
    return char_text

def load_glove(filename):
    '''

    2018-11-14: add supporting word2vector

    '''
    word_dic = {}
    if 'glove' in filename:
        print('\nload word dictionary starting!')

        with open(filename, encoding='utf-8') as fr:
            lines = [line for line in fr]
            for line in lines:
                values = line.split()
                word = values[0]
                coefs = np.asarray(values[1:], dtype='float32')
                word_dic[word] = coefs

        print('load word dictionary ending!\n')
    else:
        print('\nload word dictionary starting!')
        with open(filename, 'rb') as fr:
            word_dic = pkl.load(fr, encoding='bytes')
        print('load word dictionary ending!\n')

    return word_dic

In [52]:
word_count_token = {}
word_count_lemma = {}
word_count_lemma_pro = {}

word_dic = load_glove('../assist/glove.vectors.pro2.win20.txt')

for key in keys_lists:
    print(key)
    samples = all_samples_concate[key]
    samples['qTEXT_token'].apply(count_word_number, args=(word_count_token,))
    samples['cTEXT_token'].apply(count_word_number, args=(word_count_token,))
    
    samples['qTEXT_lemma'].apply(count_word_number, args=(word_count_lemma,))
    samples['cTEXT_lemma'].apply(count_word_number, args=(word_count_lemma,))
    
    samples['qTEXT_lemma_pro'].apply(count_word_number, args=(word_count_lemma_pro,))
    samples['cTEXT_lemma_pro'].apply(count_word_number, args=(word_count_lemma_pro,))

load word dictionary starting!
load word dictionary ending!

15dev.xml
15test.xml
15train.xml
16dev.xml
16test.xml
16train1.xml
16train2.xml
17test.xml

In [53]:
savepath = '../assist'
max_vocab = 10000  # 最大词汇数量

print('\n--------------------------------------')
word_count_ = sorted(word_count_token.items(), key=lambda x: x[1], reverse=True)
print('\t获得word2index并保存, 总词数为{}'.format(len(word_count_)))
with open(os.path.join(savepath, 'word_count_token.json'), 'w') as fw:
    json.dump(word_count_, fw)

word_count_ = word_count_[:max_vocab]
word2index_token = {word: index + 1 for index, (word, _) in enumerate(word_count_)}
print('\t\t总词数为：%d' % len(word2index_token))
with open(os.path.join(savepath, 'word2index_token.json'), 'w') as fw:
    json.dump(word2index_token, fw)

    
print('\n--------------------------------------')
word_count_ = sorted(word_count_lemma.items(), key=lambda x: x[1], reverse=True)
print('\t获得word2index并保存, 总词数为{}'.format(len(word_count_)))
with open(os.path.join(savepath, 'word_count_lemma.json'), 'w') as fw:
    json.dump(word_count_, fw)

word_count_ = word_count_[:max_vocab]
word2index_lemma = {word: index + 1 for index, (word, _) in enumerate(word_count_)}
print('\t\t总词数为：%d' % len(word2index_lemma))
with open(os.path.join(savepath, 'word2index_lemma.json'), 'w') as fw:
    json.dump(word2index_lemma, fw)

    
print('\n--------------------------------------')
word_count_ = sorted(word_count_lemma_pro.items(), key=lambda x: x[1], reverse=True)
print('\t获得word2index并保存, 总词数为{}'.format(len(word_count_)))
with open(os.path.join(savepath, 'word_count_lemma_pro.json'), 'w') as fw:
    json.dump(word_count_, fw)

word_count_ = word_count_[:max_vocab]
word2index_lemma_pro = {word: index + 1 for index, (word, _) in enumerate(word_count_)}
print('\t\t总词数为：%d' % len(word2index_lemma_pro))
with open(os.path.join(savepath, 'word2index_lemma_pro.json'), 'w') as fw:
    json.dump(word2index_lemma_pro, fw)

--------------------------------------
	获得word2index并保存, 总词数为66584
		总词数为：10000

--------------------------------------
	获得word2index并保存, 总词数为62735
		总词数为：10000

--------------------------------------
	获得word2index并保存, 总词数为41543
		总词数为：10000

In [54]:
all_samples_concate['15dev.xml'].head(2)

,q_id,c_id,q_category,q_subject,q_body,cTEXT,Relevance,q_userid,c_userid,qc_mark,...,Rrel_index,qTEXT_token,cTEXT_token,q_position_index,c_position_index,q_segment_index,qTEXT_lemma,cTEXT_lemma,qTEXT_lemma_pro,cTEXT_lemma_pro
0,Q2481,Q2481_C1,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,If you are single then its ok you can enjoy.,PotentiallyUseful,U8902,U7263,0,...,1,"[from, dubai, to, qatar, s_e_p, i, am, current...","[if, you, are, single, then, its, ok, you, can...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]","[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[from, dubai, to, qatar, s_e_p, i, am, current...","[if, you, are, single, then, it, ok, you, can,...","[from, dubai, to, qatar, s, _, e, _, p, i, am,...","[if, you, are, single, then, it, ok, you, can,..."
1,Q2481,Q2481_C2,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,depends on where the accommodation is.. how ma...,Good,U8902,U604,0,...,0,"[from, dubai, to, qatar, s_e_p, i, am, current...","[depends, on, where, the, accommodation, is..,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[from, dubai, to, qatar, s_e_p, i, am, current...","[depends, on, where, the, accommodation, is..,...","[from, dubai, to, qatar, s, _, e, _, p, i, am,...","[depends, on, where, the, accommodation, is, ...."

In [55]:
for key in keys_lists:
    print(key)
    samples = all_samples_concate[key]
    token_count = len(word2index_token)
    token_replace_func = lambda sent: [word2index_token.get(x, token_count+1) 
#                                        if x != "s_e_p" else word2index_token["[SEP]"] 
                                       for x in sent]
    samples['qTEXT_token_index'] = samples['qTEXT_token'].apply(token_replace_func)
    samples['cTEXT_token_index'] = samples['cTEXT_token'].apply(token_replace_func)
    
    lemma_count = len(word2index_lemma)
    lemma_replace_func = lambda sent: [word2index_lemma.get(x, lemma_count+1)
#                                        if x != "s_e_p" else word2index_lemma["[SEP]"]
                                       for x in sent]
    samples['qTEXT_lemma_index'] = samples['qTEXT_lemma'].apply(lemma_replace_func)
    samples['cTEXT_lemma_index'] = samples['cTEXT_lemma'].apply(lemma_replace_func)
    
    lemma_pro_count = len(word2index_lemma_pro)
    lemma_pro_replace_func = lambda sent: [word2index_lemma_pro.get(x, lemma_pro_count+1)
#                                            if x != "s_e_p" else word2index_lemma_pro["[SEP]"]
                                           for x in sent]
    samples['qTEXT_lemma_pro_index'] = samples['qTEXT_lemma_pro'].apply(lemma_pro_replace_func)
    samples['cTEXT_lemma_pro_index'] = samples['cTEXT_lemma_pro'].apply(lemma_pro_replace_func)

15dev.xml
15test.xml
15train.xml
16dev.xml
16test.xml
16train1.xml
16train2.xml
17test.xml

In [56]:
all_samples_concate['15dev.xml'].head(2)

,q_id,c_id,q_category,q_subject,q_body,cTEXT,Relevance,q_userid,c_userid,qc_mark,...,qTEXT_lemma,cTEXT_lemma,qTEXT_lemma_pro,cTEXT_lemma_pro,qTEXT_token_index,cTEXT_token_index,qTEXT_lemma_index,cTEXT_lemma_index,qTEXT_lemma_pro_index,cTEXT_lemma_pro_index
0,Q2481,Q2481_C1,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,If you are single then its ok you can enjoy.,PotentiallyUseful,U8902,U7263,0,...,"[from, dubai, to, qatar, s_e_p, i, am, current...","[if, you, are, single, then, it, ok, you, can,...","[from, dubai, to, qatar, s, _, e, _, p, i, am,...","[if, you, are, single, then, it, ok, you, can,...","[42, 210, 4, 23, 13, 5, 58, 433, 151, 50, 8, 2...","[24, 11, 21, 426, 119, 97, 345, 11, 18, 550, 1]","[42, 219, 4, 23, 14, 5, 57, 457, 156, 50, 8, 2...","[24, 11, 21, 429, 124, 13, 350, 11, 18, 572, 1]","[45, 221, 4, 26, 15, 6, 18, 6, 16, 3, 60, 458,...","[27, 13, 23, 421, 125, 17, 308, 13, 20, 568, 1]"
1,Q2481,Q2481_C2,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,depends on where the accommodation is.. how ma...,Good,U8902,U604,0,...,"[from, dubai, to, qatar, s_e_p, i, am, current...","[depends, on, where, the, accommodation, is..,...","[from, dubai, to, qatar, s, _, e, _, p, i, am,...","[depends, on, where, the, accommodation, is, ....","[42, 210, 4, 23, 13, 5, 58, 433, 151, 50, 8, 2...","[634, 30, 60, 3, 682, 5502, 48, 129, 110, 38, ...","[42, 219, 4, 23, 14, 5, 57, 457, 156, 50, 8, 2...","[655, 30, 59, 3, 668, 5050, 48, 134, 111, 38, ...","[45, 221, 4, 26, 15, 6, 18, 6, 16, 3, 60, 458,...","[658, 31, 63, 2, 662, 11, 1, 52, 139, 114, 42,..."

In [57]:
print('\n--------------------------------------')
print('\t作嵌入矩阵并保存\n')
dim = word_dic['word'].shape[0]
embedding_matrix_token = np.random.randn(len(word2index_token) + 1, dim)
embedding_matrix_token[0] = np.zeros((dim, ), dtype='float32')
for word, index in word2index_token.items():
    if word in word_dic:
        embedding_matrix_token[index] = word_dic[word]
    if word == "s_e_p":
        embedding_matrix_token[index] = word_dic["[SEP]"]
with open(os.path.join(savepath, 'embedding_matrix_token.pkl'), 'wb') as fw:
    pkl.dump(embedding_matrix_token, fw)

    
print('\n--------------------------------------')
print('\t作嵌入矩阵并保存\n')
embedding_matrix_lemma = np.random.randn(len(word2index_lemma) + 1, dim)
embedding_matrix_lemma[0] = np.zeros((dim, ), dtype='float32')
for word, index in word2index_lemma.items():
    if word in word_dic:
        embedding_matrix_lemma[index] = word_dic[word]
    if word == "s_e_p":
        embedding_matrix_lemma[index] = word_dic["[SEP]"]
with open(os.path.join(savepath, 'embedding_matrix_lemma.pkl'), 'wb') as fw:
    pkl.dump(embedding_matrix_lemma, fw)

    
print('\n--------------------------------------')
print('\t作嵌入矩阵并保存\n')
embedding_matrix_lemma_pro = np.random.randn(len(word2index_lemma_pro) + 1, dim)
embedding_matrix_lemma_pro[0] = np.zeros((dim, ), dtype='float32')
for word, index in word2index_lemma_pro.items():
    if word in word_dic:
        embedding_matrix_lemma_pro[index] = word_dic[word]
    if word == "s_e_p":
        embedding_matrix_lemma_pro[index] = word_dic["[SEP]"]
with open(os.path.join(savepath, 'embedding_matrix_lemma_pro.pkl'), 'wb') as fw:
    pkl.dump(embedding_matrix_lemma_pro, fw)

--------------------------------------
	作嵌入矩阵并保存


--------------------------------------
	作嵌入矩阵并保存


--------------------------------------
	作嵌入矩阵并保存

In [58]:
all_samples_concate['15dev.xml'].head(2)

,q_id,c_id,q_category,q_subject,q_body,cTEXT,Relevance,q_userid,c_userid,qc_mark,...,qTEXT_lemma,cTEXT_lemma,qTEXT_lemma_pro,cTEXT_lemma_pro,qTEXT_token_index,cTEXT_token_index,qTEXT_lemma_index,cTEXT_lemma_index,qTEXT_lemma_pro_index,cTEXT_lemma_pro_index
0,Q2481,Q2481_C1,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,If you are single then its ok you can enjoy.,PotentiallyUseful,U8902,U7263,0,...,"[from, dubai, to, qatar, s_e_p, i, am, current...","[if, you, are, single, then, it, ok, you, can,...","[from, dubai, to, qatar, s, _, e, _, p, i, am,...","[if, you, are, single, then, it, ok, you, can,...","[42, 210, 4, 23, 13, 5, 58, 433, 151, 50, 8, 2...","[24, 11, 21, 426, 119, 97, 345, 11, 18, 550, 1]","[42, 219, 4, 23, 14, 5, 57, 457, 156, 50, 8, 2...","[24, 11, 21, 429, 124, 13, 350, 11, 18, 572, 1]","[45, 221, 4, 26, 15, 6, 18, 6, 16, 3, 60, 458,...","[27, 13, 23, 421, 125, 17, 308, 13, 20, 568, 1]"
1,Q2481,Q2481_C2,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,depends on where the accommodation is.. how ma...,Good,U8902,U604,0,...,"[from, dubai, to, qatar, s_e_p, i, am, current...","[depends, on, where, the, accommodation, is..,...","[from, dubai, to, qatar, s, _, e, _, p, i, am,...","[depends, on, where, the, accommodation, is, ....","[42, 210, 4, 23, 13, 5, 58, 433, 151, 50, 8, 2...","[634, 30, 60, 3, 682, 5502, 48, 129, 110, 38, ...","[42, 219, 4, 23, 14, 5, 57, 457, 156, 50, 8, 2...","[655, 30, 59, 3, 668, 5050, 48, 134, 111, 38, ...","[45, 221, 4, 26, 15, 6, 18, 6, 16, 3, 60, 458,...","[658, 31, 63, 2, 662, 11, 1, 52, 139, 114, 42,..."

In [59]:
for key in keys_lists:
    print(key)
    samples = all_samples_concate[key]
    process_char = lambda sent: pad_sequences(char_tokenizer(sent), maxlen=20, padding='post', truncating='post')
    samples['qTEXT_token_char_index'] = samples['qTEXT_token'].apply(process_char)
    samples['cTEXT_token_char_index'] = samples['cTEXT_token'].apply(process_char)
    
    samples['qTEXT_lemma_char_index'] = samples['qTEXT_lemma'].apply(process_char)
    samples['cTEXT_lemma_char_index'] = samples['cTEXT_lemma'].apply(process_char)
    
    samples['qTEXT_lemma_pro_char_index'] = samples['qTEXT_lemma_pro'].apply(process_char)
    samples['cTEXT_lemma_pro_char_index'] = samples['cTEXT_lemma_pro'].apply(process_char)

15dev.xml
15test.xml
15train.xml
16dev.xml
16test.xml
16train1.xml
16train2.xml
17test.xml

In [60]:
all_samples_concate['15dev.xml'].head(2)

,q_id,c_id,q_category,q_subject,q_body,cTEXT,Relevance,q_userid,c_userid,qc_mark,...,qTEXT_lemma_index,cTEXT_lemma_index,qTEXT_lemma_pro_index,cTEXT_lemma_pro_index,qTEXT_token_char_index,cTEXT_token_char_index,qTEXT_lemma_char_index,cTEXT_lemma_char_index,qTEXT_lemma_pro_char_index,cTEXT_lemma_pro_char_index
0,Q2481,Q2481_C1,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,If you are single then its ok you can enjoy.,PotentiallyUseful,U8902,U7263,0,...,"[42, 219, 4, 23, 14, 5, 57, 457, 156, 50, 8, 2...","[24, 11, 21, 429, 124, 13, 350, 11, 18, 572, 1]","[45, 221, 4, 26, 15, 6, 18, 6, 16, 3, 60, 458,...","[27, 13, 23, 421, 125, 17, 308, 13, 20, 568, 1]","[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[9, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[9, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[9, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
1,Q2481,Q2481_C2,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,depends on where the accommodation is.. how ma...,Good,U8902,U604,0,...,"[42, 219, 4, 23, 14, 5, 57, 457, 156, 50, 8, 2...","[655, 30, 59, 3, 668, 5050, 48, 134, 111, 38, ...","[45, 221, 4, 26, 15, 6, 18, 6, 16, 3, 60, 458,...","[658, 31, 63, 2, 662, 11, 1, 52, 139, 114, 42,...","[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[4, 5, 16, 5, 14, 4, 19, 0, 0, 0, 0, 0, 0, 0,...","[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[4, 5, 16, 5, 14, 4, 19, 0, 0, 0, 0, 0, 0, 0,...","[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[4, 5, 16, 5, 14, 4, 19, 0, 0, 0, 0, 0, 0, 0,..."

In [61]:
print('\n--------------------------------------')
print('\tsave char2index')
print('\t\tthe number of charactor：%d' % len(char2index))
with open(os.path.join(savepath, 'char2index.json'), 'w') as fw:
    json.dump(char2index, fw)

--------------------------------------
	save char2index
		the number of charactor：334

In [62]:
for key in keys_lists:
    print(key)
    samples = all_samples_concate[key]
    
    samples['qTEXT_len'] = samples['qTEXT_token'].apply(len)
    samples['cTEXT_len'] = samples['cTEXT_token'].apply(len)
    
    samples['qTEXT_pro_len'] = samples['qTEXT_lemma_pro'].apply(len)
    samples['cTEXT_pro_len'] = samples['cTEXT_lemma_pro'].apply(len)

15dev.xml
15test.xml
15train.xml
16dev.xml
16test.xml
16train1.xml
16train2.xml
17test.xml

In [63]:
all_samples_concate['15dev.xml'].head(2)

,q_id,c_id,q_category,q_subject,q_body,cTEXT,Relevance,q_userid,c_userid,qc_mark,...,qTEXT_token_char_index,cTEXT_token_char_index,qTEXT_lemma_char_index,cTEXT_lemma_char_index,qTEXT_lemma_pro_char_index,cTEXT_lemma_pro_char_index,qTEXT_len,cTEXT_len,qTEXT_pro_len,cTEXT_pro_len
0,Q2481,Q2481_C1,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,If you are single then its ok you can enjoy.,PotentiallyUseful,U8902,U7263,0,...,"[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[9, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[9, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[9, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",52,11,60,11
1,Q2481,Q2481_C2,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,depends on where the accommodation is.. how ma...,Good,U8902,U604,0,...,"[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[4, 5, 16, 5, 14, 4, 19, 0, 0, 0, 0, 0, 0, 0,...","[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[4, 5, 16, 5, 14, 4, 19, 0, 0, 0, 0, 0, 0, 0,...","[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[4, 5, 16, 5, 14, 4, 19, 0, 0, 0, 0, 0, 0, 0,...",52,61,60,64

In [64]:
for key in keys_lists:
    print('\n\n', key)
    samples = all_samples_concate[key]
    print('------  qTEXT length -------')
    print(samples['qTEXT_len'].describe([0.8, 0.9, 0.95, 0.98]))
    print('------  cTEXT length -------')
    print(samples['cTEXT_len'].describe([0.8, 0.9, 0.95, 0.98]))
    
    print('------  qTEXT lemma pro length -------')
    print(samples['qTEXT_pro_len'].describe([0.8, 0.9, 0.95, 0.98]))
    print('------  cTEXT lemma pro length -------')
    print(samples['cTEXT_pro_len'].describe([0.8, 0.9, 0.95, 0.98]))

 15dev.xml
------  qTEXT length -------
count    1529.000000
mean       46.712230
std        21.728775
min         9.000000
50%        45.000000
80%        68.000000
90%        79.000000
95%        84.000000
98%        91.000000
max       108.000000
Name: qTEXT_len, dtype: float64
------  cTEXT length -------
count    1529.000000
mean       34.386527
std        48.396544
min         1.000000
50%        23.000000
80%        50.000000
90%        75.000000
95%        96.000000
98%       130.000000
max      1346.000000
Name: cTEXT_len, dtype: float64
------  qTEXT lemma pro length -------
count    1529.000000
mean       51.325049
std        22.003680
min        13.000000
50%        49.000000
80%        73.000000
90%        84.200000
95%        90.000000
98%        96.000000
max       118.000000
Name: qTEXT_pro_len, dtype: float64
------  cTEXT lemma pro length -------
count    1529.000000
mean       33.523872
std        48.462712
min         1.000000
50%        22.000000
80%        49.000000
90%        72.000000
95%        95.000000
98%       130.880000
max      1356.000000
Name: cTEXT_pro_len, dtype: float64


 15test.xml
------  qTEXT length -------
count    1876.000000
mean       45.797441
std        23.901476
min         5.000000
50%        43.000000
80%        68.000000
90%        78.000000
95%        90.250000
98%        98.000000
max       108.000000
Name: qTEXT_len, dtype: float64
------  cTEXT length -------
count    1876.000000
mean       35.650853
std        40.809204
min         1.000000
50%        23.000000
80%        53.000000
90%        80.000000
95%       106.000000
98%       141.500000
max       656.000000
Name: cTEXT_len, dtype: float64
------  qTEXT lemma pro length -------
count    1876.000000
mean       50.248401
std        24.535213
min         8.000000
50%        47.000000
80%        75.000000
90%        84.000000
95%        94.500000
98%       102.500000
max       113.000000
Name: qTEXT_pro_len, dtype: float64
------  cTEXT lemma pro length -------
count    1876.000000
mean       34.092751
std        40.638949
min         1.000000
50%        22.000000
80%        50.000000
90%        75.500000
95%       105.250000
98%       142.000000
max       682.000000
Name: cTEXT_pro_len, dtype: float64


 15train.xml
------  qTEXT length -------
count    14893.000000
mean        46.745719
std         21.780108
min          5.000000
50%         44.000000
80%         67.000000
90%         80.000000
95%         86.000000
98%         94.000000
max        112.000000
Name: qTEXT_len, dtype: float64
------  cTEXT length -------
count    14893.000000
mean        34.950648
std         43.266391
min          1.000000
50%         23.000000
80%         51.000000
90%         75.000000
95%        104.000000
98%        150.000000
max       1753.000000
Name: cTEXT_len, dtype: float64
------  qTEXT lemma pro length -------
count    14893.000000
mean        51.112469
std         22.113989
min          9.000000
50%         48.000000
80%         72.000000
90%         85.000000
95%         91.000000
98%         99.000000
max        115.000000
Name: qTEXT_pro_len, dtype: float64
------  cTEXT lemma pro length -------
count    14893.000000
mean        33.998657
std         41.255902
min          0.000000
50%         22.000000
80%         49.000000
90%         72.000000
95%        102.000000
98%        151.000000
max       1206.000000
Name: cTEXT_pro_len, dtype: float64


 16dev.xml
------  qTEXT length -------
count    2440.000000
mean       53.581967
std        25.135252
min         9.000000
50%        51.000000
80%        77.000000
90%        89.000000
95%       101.000000
98%       107.000000
max       122.000000
Name: qTEXT_len, dtype: float64
------  cTEXT length -------
count    2440.000000
mean       36.193852
std        37.545333
min         1.000000
50%        24.000000
80%        53.000000
90%        81.000000
95%       111.000000
98%       162.220000
max       234.000000
Name: cTEXT_len, dtype: float64
------  qTEXT lemma pro length -------
count    2440.000000
mean       57.561475
std        25.458331
min        11.000000
50%        55.000000
80%        81.000000
90%        94.000000
95%       102.000000
98%       114.000000
max       125.000000
Name: qTEXT_pro_len, dtype: float64
------  cTEXT lemma pro length -------
count    2440.000000
mean       36.801230
std        38.293651
min         1.000000
50%        25.000000
80%        54.000000
90%        82.000000
95%       112.050000
98%       165.220000
max       277.000000
Name: cTEXT_pro_len, dtype: float64


 16test.xml
------  qTEXT length -------
count    3270.000000
mean       55.070336
std        25.845825
min         7.000000
50%        54.000000
80%        80.000000
90%        91.000000
95%        99.000000
98%       106.000000
max       120.000000
Name: qTEXT_len, dtype: float64
------  cTEXT length -------
count    3270.000000
mean       37.281040
std        37.194629
min         1.000000
50%        25.000000
80%        57.000000
90%        82.000000
95%       113.000000
98%       157.620000
max       246.000000
Name: cTEXT_len, dtype: float64
------  qTEXT lemma pro length -------
count    3270.000000
mean       59.235474
std        26.234283
min        11.000000
50%        57.000000
80%        85.000000
90%        96.000000
95%       104.000000
98%       114.000000
max       122.000000
Name: qTEXT_pro_len, dtype: float64
------  cTEXT lemma pro length -------
count    3270.000000
mean       37.858716
std        37.750403
min         1.000000
50%        26.000000
80%        58.000000
90%        84.000000
95%       113.000000
98%       159.000000
max       236.000000
Name: cTEXT_pro_len, dtype: float64


 16train1.xml
------  qTEXT length -------
count    14110.000000
mean        58.352941
std         25.927138
min          7.000000
50%         58.000000
80%         83.000000
90%         93.000000
95%        101.000000
98%        106.000000
max        124.000000
Name: qTEXT_len, dtype: float64
------  cTEXT length -------
count    14110.000000
mean        41.561871
std         40.864218
min          1.000000
50%         28.000000
80%         62.000000
90%         93.000000
95%        127.000000
98%        180.000000
max        268.000000
Name: cTEXT_len, dtype: float64
------  qTEXT lemma pro length -------
count    14110.000000
mean        62.450035
std         26.440674
min         11.000000
50%         62.000000
80%         88.000000
90%         98.000000
95%        106.000000
98%        111.000000
max        125.000000
Name: qTEXT_pro_len, dtype: float64
------  cTEXT lemma pro length -------
count    14110.000000
mean        42.267257
std         41.480170
min          1.000000
50%         29.000000
80%         63.000000
90%         95.000000
95%        129.000000
98%        181.820000
max        256.000000
Name: cTEXT_pro_len, dtype: float64


 16train2.xml
------  qTEXT length -------
count    3790.000000
mean       55.717678
std        26.567352
min         7.000000
50%        56.000000
80%        81.000000
90%        92.000000
95%       101.000000
98%       108.000000
max       127.000000
Name: qTEXT_len, dtype: float64
------  cTEXT length -------
count    3790.000000
mean       36.911082
std        36.033755
min         1.000000
50%        26.000000
80%        56.000000
90%        80.000000
95%       109.000000
98%       147.000000
max       232.000000
Name: cTEXT_len, dtype: float64
------  qTEXT lemma pro length -------
count    3790.000000
mean       59.609499
std        26.869587
min        11.000000
50%        59.000000
80%        85.000000
90%        96.000000
95%       103.000000
98%       112.000000
max       131.000000
Name: qTEXT_pro_len, dtype: float64
------  cTEXT lemma pro length -------
count    3790.000000
mean       37.333245
std        36.423922
min         1.000000
50%        26.000000
80%        57.000000
90%        81.000000
95%       111.000000
98%       148.440000
max       236.000000
Name: cTEXT_pro_len, dtype: float64


 17test.xml
------  qTEXT length -------
count    2930.000000
mean       60.778157
std        29.596269
min         8.000000
50%        55.000000
80%        91.000000
90%       105.000000
95%       112.000000
98%       118.000000
max       128.000000
Name: qTEXT_len, dtype: float64
------  cTEXT length -------
count    2930.000000
mean       39.460751
std        40.263938
min         1.000000
50%        27.000000
80%        58.000000
90%        88.100000
95%       120.000000
98%       162.000000
max       412.000000
Name: cTEXT_len, dtype: float64
------  qTEXT lemma pro length -------
count    2930.000000
mean       65.310580
std        30.145246
min        12.000000
50%        60.000000
80%        98.000000
90%       111.000000
95%       118.000000
98%       125.000000
max       130.000000
Name: qTEXT_pro_len, dtype: float64
------  cTEXT lemma pro length -------
count    2930.000000
mean       40.364505
std        41.605960
min         1.000000
50%        27.000000
80%        60.000000
90%        90.000000
95%       122.000000
98%       167.420000
max       448.000000
Name: cTEXT_pro_len, dtype: float64

In [65]:
with open(os.path.join('../data', 'dataset.pkl'), 'wb') as fw:
    pkl.dump(all_samples_concate, fw)

In [66]:
all_samples_concate['15dev.xml'].head(2)

,q_id,c_id,q_category,q_subject,q_body,cTEXT,Relevance,q_userid,c_userid,qc_mark,...,qTEXT_token_char_index,cTEXT_token_char_index,qTEXT_lemma_char_index,cTEXT_lemma_char_index,qTEXT_lemma_pro_char_index,cTEXT_lemma_pro_char_index,qTEXT_len,cTEXT_len,qTEXT_pro_len,cTEXT_pro_len
0,Q2481,Q2481_C1,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,If you are single then its ok you can enjoy.,PotentiallyUseful,U8902,U7263,0,...,"[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[9, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[9, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[9, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",52,11,60,11
1,Q2481,Q2481_C2,Life in Qatar,from DUBAI to QATAR,i am currently working here in dubai and i got...,depends on where the accommodation is.. how ma...,Good,U8902,U604,0,...,"[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[4, 5, 16, 5, 14, 4, 19, 0, 0, 0, 0, 0, 0, 0,...","[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[4, 5, 16, 5, 14, 4, 19, 0, 0, 0, 0, 0, 0, 0,...","[[6, 18, 15, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[[4, 5, 16, 5, 14, 4, 19, 0, 0, 0, 0, 0, 0, 0,...",52,61,60,64